import { App } from '../types';

export const apps: App[] = [
  {
    id: 'events',
    name: 'Events',
    description: 'Gestion des evenements',
    icon: '??',
    path: '/apps/events',
    roles: ['events.read'],
    color: '#4F46E5',
  },
  {
    id: 'booth',
    name: 'Booth',
    description: 'Configuration des bornes, downloads, retry',
    icon: '???',
    path: '/apps/booth',
    roles: ['booth.read'],
    color: '#059669',
    externalUrl: 'http://booth.konitys.fr',
  },
  {
    id: 'stocks',
    name: 'Stocks',
    description: 'Gestion des stocks',
    icon: '??',
    path: '/apps/stocks',
    roles: ['stocks.read'],
    color: '#D97706',
  },
  {
    id: 'subscriptions',
    name: 'Abonnements',
    description: 'Gestion des abonnements',
    icon: '??',
    path: '/apps/subscriptions',
    roles: ['subscriptions.read'],
    color: '#DC2626',
  },
  {
    id: 'support',
    name: 'Support',
    description: 'Support & Knowledge base',
    icon: '??',
    path: '/apps/support',
    roles: ['support.read'],
    color: '#7C3AED',
  },
  {
    id: 'antenne',
    name: 'Antenne',
    description: 'Gestion des antennes',
    icon: '??',
    path: '/apps/antenne',
    roles: ['antenne.read'],
    color: '#0891B2',
    externalUrl: 'http://antenne.konitys.fr',
  },
];
